### ISSUE TITLE
Range: bytes=0-

### ISSUE THREAD

**Issue by elebescond** [jshttp/range-parser#11]
Chrome (version: Version 42.0.2311.135 linux) generates a Range request with this value:

    Range: bytes=0-

range-parser returns :

    { start: 0, end: 0 }

Some libraries (send) seems to be disturb by this value ...

I'm using this patch:

    if(end == start) {
      end = size-start-1;
    }

But i'm sure that it's true?

Thanks

**Comment by dougwilson** [comment]
Hi! The `end` should be the value from the `len` argument, I believe. Can you debug and post here what the call to this library looks like? i.e. given the call `parseRange(len, str)`, what is the value for `len` and what is the value for `str` that results in that return?

**Comment by elebescond** [comment]
Input

    len = 392520, str = bytes=0-

Output

    parseRange result: [ { start: 0, end: 0 }, type: 'bytes' ]

**Comment by dougwilson** [comment]
Perhaps you are using an old version of this library? The current version does not have this issue:
```
$ node -pe 'require("range-parser/package").version'
1.0.2

$ node -pe 'require("range-parser")(392520,"bytes=0-")'
[ { start: 0, end: 392519 }, type: 'bytes' ]
```
