### ISSUE TITLE
Why is the last-byte-pos set to the size when a requested part's end is after the maximum size of the resource?

### ISSUE THREAD

**Issue by sammbeller** [jshttp/range-parser#19]
I've asked this question on [StackOverflow](https://stackoverflow.com/questions/56975750/why-does-range-finder-set-the-last-byte-pos-to-the-size-when-a-requested-parts) as well because there doesn't seem to be much activity here. Seems I'm misunderstanding something?

**Comment by dougwilson** [comment]
It's just because that is the interface of this module: it is made to parse the range header so you can use it to send a resource. The returned ranges will then always fit within the size of the resource you're intending to send to the client.

If the client requests past the end, the RFC says to just assume they meant the actual end of the resource (which is `size`).

Range RFC: https://tools.ietf.org/html/rfc7233

> If the last-byte-pos value is
   absent, or if the value is greater than or equal to the current
   length of the representation data, the byte range is interpreted as
   the remainder of the representation (i.e., the server replaces the
   value of last-byte-pos with a value that is one less than the current
   length of the selected representation).

**Comment by sammbeller** [comment]
I'm sorry I still don't quite understand. Does this mean that size must be greater than the overall size of the requested resource and not just the acceptable size of a requested portion?

**Comment by dougwilson** [comment]
I'm sorry, I don't understand your question now, haha. Maybe there is a better way to phrase it? Or maybe you can provide some background?

The specific lines in this code you pointed to implements that specific part of the specification. If your question is about the specification itself and not about that we didn't implement it right, then you may need to add the specification writers. If it's about this implementation, perhaps if you could point to the part in our implementation that doesn't match a particular part in the specification? (i.e. where we deviated from the specs)

**Comment by dougwilson** [comment]
So I see the SO post you made is now deleted, so if it helps:

@sammbeller is asking about the following code part:

https://github.com/jshttp/range-parser/blob/v1.2.1/index.js#L60-L63

This implements the following from https://tools.ietf.org/html/rfc7233

> If the last-byte-pos value is [...] greater than or equal to the current length of the representation data, the byte range is interpreted as the remainder of the representation (i.e., the server replaces the value of last-byte-pos with a value that is one less than the current length of the selected representation).

The `size` variable is the "current length of the representation data", the `end` variable is the "last-byte-pos value"

**Comment by sammbeller** [comment]
I guess my question is, what does the `size` parameter represent? From the README "`size` is the maximum size of the resource". Does this refer to the resource of which a portion is being requested or  to the size of the portion itself?

My assumption was that it represented the maximum allowable size of the requested portion but that seems to be incorrect.

In my usecase. A request is being made for a portion with range `bytes=180224-189908` and I've set size to `100000` I would expect this to succeed but its failing.

**Comment by dougwilson** [comment]
Ah, I see what you're saying: the does are confusing as they create ambiguity since they do not properly reflect the terms used in the HTTP specifications. Yes, it should be changed to read "`size`  is the size of the selected representation that is to be partitioned into subranges" perhaps?

**Comment by sammbeller** [comment]
That clarifies things. Thanks so much!

**Comment by dougwilson** [comment]
Thanks again for the feedback and sorry for the confusion. I have updating the wording in https://github.com/jshttp/range-parser/commit/5f48dfc7996b18242dfa1fbddcc03f39b42a4554
