### ISSUE TITLE
rangeParser is not a function

### ISSUE THREAD

**Issue by digimbyte** [jshttp/range-parser#22]
Im working with a backend node server for our api and I need to use range parser

here is how I have it used:
```
import RangeParse from 'range-parser';
const ranges = RangeParse(100000, request.range, { combine: true });
```
this should yield the default export which indicates that this is a valid method. but I am recieving a crash error of:
```js
 (0 , range_parser_1.default) is not a function
TypeError: (0 , range_parser_1.default) is not a function```

**Comment by dougwilson** [comment]
Hi @digimbyte sorry you are having issues. The way to require this module is at the top of the readme: https://github.com/jshttp/range-parser#api I hope that helps!

**Comment by digimbyte** [comment]
I'm surprised its not TS module import compliant

**Comment by dougwilson** [comment]
I'm not sure what a TS module is. This is a CommonJS module written in Javascript for the Node.js platform published to npm, if that helps.

**Comment by digimbyte** [comment]
TypeScript is a Type safe expansion of JavaScript, it uses module imports rather than 'require'
you've never heard of it? its basically if JS wanted to be C#

**Comment by dougwilson** [comment]
Hi, yes, I have head of typescript. I'm sorry I didn't understand that is what you meant when you abbreviated ts, please no need to be rude. I just write in javascript, though. If there is something you want to contribute to the project, you are welcome to do so.
